---
- name: Install Grafana Agent
  ansible.builtin.package:
    name: grafana-agent
    state: present

- name: Start Grafana Agent
  ansible.builtin.service:
    name: grafana-agent
    state: started
    enabled: true
