namespace: evgeni
name: grafana
version: 0.1.0
readme: README.md
authors:
  - Evgeni Golov (github.com/evgeni)
description: null
license_file: LICENSE
tags:
  - grafana
  - grafana-agent
repository: https://github.com/evgeni/evgeni.grafana
homepage: https://github.com/evgeni/evgeni.grafana
issues: https://github.com/evgeni/evgeni.grafana/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - venv
