---
dependency:
  name: galaxy
driver:
  name: ${DRIVER_NAME:-podman}
platforms:
  - name: centosstream9
    image: quay.io/centos/centos:stream9
provisioner:
  name: ansible
verifier:
  name: ansible
