---
dependency:
  name: galaxy
driver:
  name: ${DRIVER_NAME:-podman}
platforms:
  - name: leap15
    image: registry.opensuse.org/opensuse/leap:15
provisioner:
  name: ansible
verifier:
  name: ansible
