---
- name: Configure Grafana repository
  ansible.builtin.deb822_repository:
    name: grafana
    types: deb
    uris: https://apt.grafana.com
    suites: stable
    components: main
    signed_by: https://apt.grafana.com/gpg.key
  notify:
    - Refresh apt repository data

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
