---
name: Test

on:
  push:
    branches:
      - devel
  pull_request:


concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.15
          - stable-2.16
          - devel
    runs-on: ubuntu-latest
    steps:
      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: sanity
          pull-request-change-detection: false

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.11"
        ansible:
          - stable-2.15
          - stable-2.16
          - devel
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Podman
        run: |
          echo 'deb http://archive.ubuntu.com/ubuntu/ noble main universe' | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y podman crun
      - name: Install Ansible
        run: pip install --upgrade https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz
      - name: Install dependencies
        run: pip install molecule molecule-plugins pytest pytest-ansible
      - name: Run tests
        run: pytest -vv --molecule roles/

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install ansible-lint
      - name: Run ansible-lint
        run: ansible-lint -vv

  check:
    if: always()

    needs:
      - sanity
      - molecule
      - ansible-lint

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
